# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='price_in_cents',
            new_name='price_cents',
        ),
    ]
