# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_gift_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gift',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
