# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_auto_20171121_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='photo',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
