# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0007_auto_20171127_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='price_cents',
            new_name='price',
        ),
    ]
