# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0008_auto_20171127_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='held',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holds', to=settings.AUTH_USER_MODEL),
        ),
    ]
