# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0009_gift_held'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='held',
            new_name='holder',
        ),
    ]
