# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0011_wishlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
