# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0012_auto_20171129_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='sku',
            field=models.BigIntegerField(blank=True),
        ),
    ]
